# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: <img src='https://griegner.github.io/assets/images/nifti.gif' width='125'>
title_separator: ''
name: Gabriel Riegner
email: 'gariegner@ucsd.edu'
description: personal website
url: 'https://griegner.github.io'
github_username: griegner
minimal_mistakes_skin: default
search: false
google_analytics: G-TC1K0Q943S

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-gallery-generator
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name    : Gabriel Riegner
  avatar  : /assets/images/bio-photo.jpg
  bio     : UC San Diego
  links:
    - label: email
      icon: fas fa-envelope
      url: mailto:gariegner@ucsd.edu

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
